# Generated by Django 2.2.6 on 2019-10-26 12:22

from django.db import migrations, models


def check_new_buildings(apps, schema_editor):
    _flat = apps.get_model('property', 'flat')
    for edtd_flat in _flat.objects.all():
        if int(edtd_flat.construction_year) >= 2015:
            edtd_flat.new_building = True
        else:
            edtd_flat.new_building = False
        print(edtd_flat)
        edtd_flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20191026_1522'),
    ]

    operations = [
        migrations.RunPython(check_new_buildings),
    ]
