# Generated by Django 2.2.6 on 2019-10-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='user_id',
            new_name='user',
        ),
    ]
