# Generated by Django 2.2.6 on 2019-10-27 18:45

from django.db import migrations
import phonenumbers


def correct_phonenumber(apps, schema_editor):
    _flat = apps.get_model('property', 'flat')
    for edtd_flat in _flat.objects.all():
        corrected_phone_number = phonenumbers.parse(
            edtd_flat.owners_phonenumber, 'RU')
        edtd_flat.owner_phone_pure = corrected_phone_number
        print(edtd_flat)
        edtd_flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(correct_phonenumber),
    ]
