# Generated by Django 2.2.6 on 2019-10-27 18:45

from django.db import migrations
import phonenumbers


def correct_phonenumber(apps, schema_editor):
    _flat = apps.get_model('property', 'flat')
    for edtd_flat in _flat.objects.all():
        corrected_phone_number = phonenumbers.parse(
            edtd_flat.owners_phonenumber, 'RU')
        print(corrected_phone_number)
        if phonenumbers.is_valid_number(corrected_phone_number):
            edtd_flat.owner_phone_pure = corrected_phone_number
        else:
            edtd_flat.owner_phone_pure = None
        print(edtd_flat)
        edtd_flat.save()


# # Для отката - предыдущая миграция:
# python manage.py migrate property 0011_flat_owner_phone_pure_data_migrate
def move_backward(apps, schema_editor):
    _flat = apps.get_model('property', 'flat')
    for edtd_flat in _flat.objects.all():
        edtd_flat.owner_phone_pure = None
        print(f'move_backward {edtd_flat}')
        edtd_flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_flat_owner_phone_pure_data_migrate'),
    ]

    operations = [
        migrations.RunPython(correct_phonenumber, move_backward),
    ]
