# Generated by Django 2.2.6 on 2019-10-29 18:36

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(db_index=True, related_name='owners_flats', to='property.Flat', verbose_name='Квартиры, в собственности'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner',
            field=models.CharField(default=datetime.datetime(2019, 10, 29, 18, 36, 38, 713082, tzinfo=utc), max_length=200, verbose_name='ФИО владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_phone_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Нормализированный Номер владельца'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(default=datetime.datetime(2019, 10, 29, 18, 36, 45, 257403, tzinfo=utc), max_length=20, verbose_name='Номер владельца'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_flat', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
