# Generated by Django 2.2.6 on 2019-10-29 18:36

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


def relocate_owner_data(apps, schema_editor):
    _flat = apps.get_model('property', 'flat')
    _owner = apps.get_model('property', 'owner')
    for flat in _flat.objects.all():
        _owner.objects.get_or_create(owner=flat.owner,
                                     owners_phonenumber=flat.owners_phonenumber,
                                     owner_phone_pure=flat.owner_phone_pure)
        print(flat)


# # Для отката - предыдущая миграция:
# python manage.py migrate property 0014_auto_20191029_2136
def move_backward(apps, schema_editor):
    _owner = apps.get_model('property', 'owner')
    for owner in _owner.objects.all():
        owner.delete()
        print(f'move_backward {owner}')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20191029_2136'),
    ]

    operations = [
        migrations.RunPython(relocate_owner_data, move_backward),
    ]
