# Generated by Django 2.2.6 on 2019-10-29 23:36

from django.conf import settings
from django.db import migrations, models
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned


def relocate_owner_schema(apps, schema_editor):
    _flat = apps.get_model('property', 'flat')
    _owner = apps.get_model('property', 'owner')
    for owner in _owner.objects.all():
        all_flats = _flat.objects.filter(owner=owner.owner)
        for flat in all_flats:
            if flat:
                owner.flat.add(flat)
                owner.save()
                print(f'{owner} владеет {all_flats}')


# # Для отката - предыдущая миграция:
# python manage.py migrate property 0017_auto_20191030_0033
def move_backward(apps, schema_editor):
    _owner = apps.get_model('property', 'owner')
    for owner in _owner.objects.all():
        if owner:
            owner.flat.set('')
            owner.save()
            print(f'move_backward {owner}')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20191030_0033'),
    ]

    operations = [
        migrations.RunPython(relocate_owner_schema, move_backward),
    ]
