# Generated by Django 2.2.6 on 2019-10-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_owner_schema_migrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_phone_pure',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
